grammar gorgotites;

gorgotita : gorgon
        | gorgonParestigmenoAristera
        | gorgonParestigmenoDexia
        | digorgon
        | digorgonParestigmenoAristera
        | digorgonParestigmenoDexia
        | trigorgon
        | trigorgonParestigmenoAristeraKato
        | trigorgonParestigmenoAristeraPano
        | trigorgonParestigmenoDexia
        | ARGON
        | IMIDIARGON
        | DIARGON
        ;

gorgon : GORGON_NEO_ANO
        | GORGON_NEO_KATO
        | GORGON_USED_ON_KENTIMATA_ABOVE_OLIGON
        | GORGON_USED_ON_YPORROI
        | GORGON_USED_ON_L116_YPORROI
        | GORGON_ANO_STA_DEXIA
        | GORGON_KATO
        | GORGON_KATO_STA_DEXIA
        ;

gorgonParestigmenoAristera :
        GORGON_PARESTIGMENON_ARISTERA
        | GORGON_LEFT_DOT_USED_ON_L116_YPORROI
        | GORGON_PARESTIGMENON_ARISTERA_STA_DEXIA
        | GORGON_LEFT_DOT_USED_ON_YPORROI
        ;

gorgonParestigmenoDexia :
        GORGON_PARESTIGMENON_DEXIA
        | GORGON_RIGHT_DOT_USED_ON_YPORROI
        | GORGON_PARESTIGMENON_DEXIA_STA_DEXIA
        ;

digorgon :
        DIGORGON
        | DIGORGON_USED_ON_KENTIMATA_ABOVE_OLIGON
        | DIGORGON_USED_ON_YPORROI
        | DIGORGON_USED_ON_L116_YPORROI
        | DIGORGON_STA_DEXIA
        ;

digorgonParestigmenoAristera :
        DIGORGON_PARESTIGMENON_ARISTERA_KATO
        | DIGORGON_PARESTIGMENON_ARISTERA_ANO
        | DIGORGON_LEFT_DOT_USED_ON_YPORROI
        | DIGORGON_PARESTIGMENON_ARISTERA_KATO_STA_DEXIA
        | DIGORGON_PARESTIGMENON_ARISTERA_ANO_STA_DEXIA
        ;

digorgonParestigmenoDexia :
        DIGORGON_PARESTIGMENON_DEXIA
        | DIGORGON_PARESTIGMENON_DEXIA_STA_DEXIA
        ;

trigorgon :
        TRIGORGON
        | TRIGORGON_USED_ON_YPORROI
        | TRIGORGON_USED_ON_L116_YPORROI
        | TRIGORGON_STA_DEXIA
        ;

trigorgonParestigmenoAristeraKato :
        TRIGORGON_LEFT_DOT_USED_ON_YPORROI
        | TRIGORGON_PARESTIGMENON_ARISTERA_KATO
        | TRIGORGON_PARESTIGMENON_ARISTERA_KATO_STA_DEXIA
        ;

trigorgonParestigmenoAristeraPano :
        TRIGORGON_PARESTIGMENON_ARISTERA_ANO
        | TRIGORGON_PARESTIGMENON_ARISTERA_ANO_STA_DEXIA
        ;

trigorgonParestigmenoDexia :
        TRIGORGON_PARESTIGMENON_DEXIA
        | TRIGORGON_PARESTIGMENON_DEXIA_STA_DEXIA
        ;

// Synagmata or Gorgotites (Synagmas or Quickeners)
GORGON_NEO_ANO : '𝂏' | 'B101' ;
GORGON_PARESTIGMENON_ARISTERA : '𝂐' | 'L096' ;
GORGON_PARESTIGMENON_DEXIA : '𝂑' | 'L049' ;
DIGORGON : '𝂒' | 'L050' ;
DIGORGON_PARESTIGMENON_ARISTERA_KATO : '𝂓' | 'L051' ;
DIGORGON_PARESTIGMENON_ARISTERA_ANO : '𝂔' | 'L052' ;
DIGORGON_PARESTIGMENON_DEXIA : '𝂕' | 'L053' ;
TRIGORGON : '𝂖' | 'L054' ;
ARGON : '𝂗' | 'B119' ;
IMIDIARGON : '𝂘' | 'B087' ;
DIARGON : '𝂙' | 'L113' ;
// Specials
GORGON_NEO_KATO : '𝃵' ;
// MK only
GORGON_USED_ON_KENTIMATA_ABOVE_OLIGON: 'B216' ;                 // /
DIGORGON_USED_ON_KENTIMATA_ABOVE_OLIGON: 'B228' ;               // //
// Gorgotites used on YPORROI
GORGON_USED_ON_YPORROI : 'B208' ;                               // /
GORGON_LEFT_DOT_USED_ON_YPORROI : 'L170' ;                      // '/
GORGON_RIGHT_DOT_USED_ON_YPORROI : 'L172' ;                     // /'
DIGORGON_USED_ON_YPORROI : 'L165' ;                             // //'
DIGORGON_LEFT_DOT_USED_ON_YPORROI : 'L167' ;                    // //'
TRIGORGON_USED_ON_YPORROI : 'L168' ;                            // ///
TRIGORGON_LEFT_DOT_USED_ON_YPORROI : 'L166' ;                   // '///
// Gorgotites used on YPORROI AT YPORROI_AND_KENTIMATA_OVER_OLIGON
GORGON_USED_ON_L116_YPORROI : 'L171' ;
DIGORGON_USED_ON_L116_YPORROI : 'L163' ;
TRIGORGON_USED_ON_L116_YPORROI : 'L162' ;
GORGON_LEFT_DOT_USED_ON_L116_YPORROI : 'L161' ;
//GORGON_RIGHT_DOT_USED_ON_L116_YPORROI : 'L033' ;
//DIGORGON_LEFT_DOT_USED_ON_L116_YPORROI : 'L035' ;
//DIGORGON_RIGHT_DOT_USED_ON_L116_YPORROI : 'L037' ;
//TRIGORGON_LEFT_DOT_USED_ON_L116_YPORROI : 'L038' ;
//TRIGORGON_RIGHT_DOT_USED_ON_L116_YPORROI : 'L040' ;

GORGON_ANO_STA_DEXIA : 'B114' ;
GORGON_KATO : 'B069' ;
GORGON_KATO_STA_DEXIA : 'B082' ;
GORGON_PARESTIGMENON_ARISTERA_STA_DEXIA : 'L126' ;
GORGON_PARESTIGMENON_DEXIA_STA_DEXIA : 'L033' ;
DIGORGON_STA_DEXIA : 'L064' ;
DIGORGON_PARESTIGMENON_ARISTERA_KATO_STA_DEXIA : 'L035' ;
DIGORGON_PARESTIGMENON_ARISTERA_ANO_STA_DEXIA : 'L036' ;
DIGORGON_PARESTIGMENON_DEXIA_STA_DEXIA : 'L037' ;
TRIGORGON_STA_DEXIA : 'L094' ;
TRIGORGON_PARESTIGMENON_ARISTERA_KATO : 'L055' ;
TRIGORGON_PARESTIGMENON_ARISTERA_KATO_STA_DEXIA : 'L038' ;
TRIGORGON_PARESTIGMENON_ARISTERA_ANO : 'L056' ;
TRIGORGON_PARESTIGMENON_ARISTERA_ANO_STA_DEXIA : 'L042' ;
TRIGORGON_PARESTIGMENON_DEXIA : 'L057' ;
TRIGORGON_PARESTIGMENON_DEXIA_STA_DEXIA : 'L040' ;